spring.application.name=quizzo

spring.datasource.url=jdbc:postgresql://localhost:5432/quizzo
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop

jwt.access-secret=E1MS+R35Bs3ZIt/ZCJEw6tA1aCFae5rC5aBAFWsUzmY=
jwt.access-ms=3600000

jwt.refresh-secret=UQNJDi0ycPYdQEbYiBhIc5d1Dd4SeXtdImdsoVRv3OA=
jwt.refresh-ms=604800000