spring.application.name=quizzo

spring.datasource.url=jdbc:postgresql://localhost:5432/quizzo
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop

jwt.secret="MDEyMzQ1Njc4OUFCQ0RFRjAxMjM0NTY3ODlBQkNERUYwMTIzNDU2Nzg5QUJDREVG"
jwt.access-ms=3600000
jwt.refresh-ms=1209600000